### ISSUE TITLE
Fatal error with the icon_select

### ISSUE THREAD

**Issue by udarts** [reduxframework/redux-extensions#329] opened 2017-04-24 21:40 UTC
Hi There,

I am using a icon_select type inside a repeater, getting the following error:
`
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/extensions/icon_select/icon_select/field_icon_select.php:88 Stack trace: #0 /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/ReduxCore/framework.php(3464): ReduxFramework_icon_select->__construct(Array, '', Object(ReduxFramework)) #1 /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/extensions/repeater/repeater/field_repeater.php(337): ReduxFramework->_field_input(Array, '') #2 /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/extensions/repeater/repeater/field_repeater.php(381): ReduxFramework_repeater->output_field(Array, 99999) #3 /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/ReduxCore/core/enqueue.php(333): ReduxFramework_repeater->localize(Array) #4 /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/ReduxCore/core/enqueue.php(350): reduxCoreEnqueue->_enqueue_field(Array) in /Applications/MAMP/htdocs/sent/wp-content/themes/sportentrainer/admin/extensions/icon_select/icon_select/field_icon_select.php on line 88`
`
When I remove the icon_select option from the options-init.php, all is fine.
Any idea why this is happening?

Cheers,

**Comment by udarts** [comment] 2017-05-01 06:07
Does anyone has the same issue with the icon_select?

**Comment by kprovance** [comment] 2017-05-01 06:09
Support URL/hash?  Purchase code (for this and repeater).

**Comment by udarts** [comment] 2017-05-01 11:02
Hereby the support URL/Hash:
http://support.redux.io/?id=UjV9ODXIxYtjb5MwhmWAqCFAbOCp9SeEuLYJ1WqtAEnOr4ZPEzmpddexrIIjoY2hspl0sJOVvf20tUd1u%2FvdSA%3D%3D

**Comment by kprovance** [comment] 2017-05-01 11:10
Purchase code?

**Comment by kprovance** [comment] 2017-05-01 11:14
Also, looking at you config, icon_select does not appear to be in use in either your panel or metaboxes.  I'm not sure how you are even getting an error at this point.

**Comment by udarts** [comment] 2017-05-01 11:27
Well I have commented out the icon_select, since it was causing issue.

**Comment by udarts** [comment] 2017-05-01 11:27
Where can I find the Purchase code?

**Comment by kprovance** [comment] 2017-05-01 19:02
Four digit number on your receipt you got via email.  But if you are not using the ectension, you should remove it from your project. Plus any others you are not using.

**Comment by udarts** [comment] 2017-05-01 19:43
Hereby the Purchase code: 6574

I want to use the icon_select, but it is causing issues, so that is why I had to disable it. Still want to use it.

**Comment by kprovance** [comment] 2017-05-01 19:45
Well, the entire point of asking for the support hash was to see your config, but that config didn;t tell me anything because it looks like you changed it.  So, let's try this again, because it's getting a bit frustrating.  Load up your project however you had it, even if you get the error, so that config is set.  I need to see it how it's failing, otherwise I cannot recrate, and then cannot help.  Aftyerward, generate a new support hash and post it.

**Comment by udarts** [comment] 2017-05-01 20:00
Ah, ok, I just did, here is the new hash again:

http://support.redux.io/?id=UjV9ODXIxYtjb5MwhmWAqCFAbOCp9SeEuLYJ1WqtAEnOr4ZPEzmpddexrIIjoY2hspl0sJOVvf20tUd1u%2FvdSA%3D%3D

**Comment by dovy** [comment] 2017-05-01 20:04
@udarts from your support URL we can see your config settings. However, within the support URL you just sent there is no icon_select field at all.

We can't debug something that isn't there.

**Comment by udarts** [comment] 2017-05-01 20:09
Hmmm, done it again, now they were visible in the backend:
http://support.redux.io/?id=UjV9ODXIxYtjb5MwhmWAqCFAbOCp9SeEuLYJ1WqtAEnOr4ZPEzmpddexrIIjoY2hspl0sJOVvf20tUd1u%2FvdSA%3D%3D

**Comment by udarts** [comment] 2017-05-01 20:10
can you see them as well?

**Comment by dovy** [comment] 2017-05-01 20:30
Odd. Just copy/paste your config where you put icon select in here.

**Comment by udarts** [comment] 2017-05-01 20:38
Ok, here is part of the config file, where the icon select is added:
`Redux::setSection( $opt_name, array(
        'title'     => __( 'Top Footer', 'sportentrainer' ),
        'id'        => 'top-footer',
        'icon'      => '',
        'fields'    => array(
            array(
                'id'        => 'top-footer-enabled',
                'type'      => 'checkbox',
                'title'     => __( 'Top footer tonen', 'sportentrainer' ),
                'subtitle'  => __( 'Inschakelen om de top footer te tonen.', 'sportentrainer' ),
            ),
            array(
                'id'        => 'top-footer-content-width',
                'type'      => 'image_select',
                'title'     => __( 'Selecteer content layout', 'sportentrainer' ),
                'subtitle'  => __( 'Je kunt kiezen tussen, boxed en wide', 'sportentrainer' ),
                'options'   => array(
                    '1' => array(
                        'alt'   => 'Boxed',
                        'img'   => ReduxFramework:: $_url . 'assets/img/general-layout-boxed.gif',
                    ),
                    '2' => array(
                        'alt'   => 'Wide',
                        'img'   => ReduxFramework:: $_url . 'assets/img/general-layout-wide.gif'
                    )
                ),
                'default'   => '1',
                'required'      => array('top-footer-enabled','=','1'),
            ),
            array(
                'id'        => 'top-footer-bg',
                'type'     => 'background',
                'compiler' => array( '.footer #top-footer.top-footer' ),
                'title'    => __('Achtergrond kleur voor de top footer', 'sportentrainer'), 
                'subtitle' => __('Kies een kleur voor de top achtergrond (standaard: #fff).', 'sportentrainer'),
                'default'   => array(
                    'background-color'  => '#FFFFFF',
                ),
                'background-repeat'     => false,
                'background-attachment' => false,
                'background-position'   => false,
                'background-image'      => false,
                'background-size'       => false,
                'preview_media'         => false,
                'preview'               => false,
                'required'      => array('top-footer-enabled','=','1'),
            ),
            array(
                'id'        => 'top-footer-begin-1',
                'type'      => 'accordion',
                'class'     => 'topfooterenabled',
                'title'     => __( 'Top Footer Blok 1', 'sportentrainer' ),
                'subtitle'  => __('Instellingen voor top footer blok 1', 'sportentrainer'),
                'position'  => 'start',
            ),
                array(
                    'id'        => 'top-footer-switch-1',
                    'type'      => 'button_set',
                    'title'     => __( 'Switch tussen widget en losse elementen', 'sportentrainer' ),
                    'subtitle'  => __( 'Hier kun je kiezen tussen widget of losse elementen met icons (website link of email, etc)', 'sportentrainer' ),
                    'options' => array(
                        '1' => 'Widget', 
                        '2' => 'Elementen', 
                        '3' => 'Menu'
                     ), 
                    'default' => '2'
                ),
                array(
                    'id'        => 'top-footer-widgets-1',
                    'type'      => 'select',
                    'title'     => __( 'Selecteer een Widget Area', 'sportentrainer' ),
                    'subtitle'  => __( 'Widget Area voor top footer block 1', 'sportentrainer' ),
                    'required'  => array('top-footer-switch-1', '=', '1'),
                    'data'      => 'sidebars',
                    'multi'     => true,
                    'sortable'  => true
                ),
                array(
                    'id'            => 'top-footer-elements-repeater-1',
                    'type'          => 'repeater',
                    'title'         => __( 'Title', 'sportentrainer' ),
                    'group_values'  => true,
                    'fields'        => array(
                        array(
                            'id'        => 'top-footer-elements-elem-icon',
                            'type'      => 'icon_select',
                            'title'     => __( 'Icon voor element', 'sportentrainer' ),
                            'subtitle'  => __( 'Selecteer icon voor element, laat leeg voor geen icon.', 'sportentrainer' ),
                            'height'    => '120px',
                            'stylesheet'    => 'http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css',
                            'prefix'    => 'fa',
                            'selector'  => 'fa-',
                        ),
                        array(
                            'id'        => 'top-footer-icon-color',
                            'type'      => 'color',
                            'title'     => __( 'Icon Kleur', 'sportentrainer' ),
                            'subtitle'  => __( 'Kies de kleur voor de icon', 'sportentrainer' ),
                            'default'   => '#FFFFFF',
                            'transparent' => false,
                        ),
                        array(
                            'id'        => 'top-footer-elements-elem-text',
                            'type'      => 'text',
                            'title'     => __( 'Tekst voor element', 'sportentrainer' ),
                            'subtitle'  => __( 'Vul tekst in, dit kan ook een url zijn, dit wordt herkend', 'sportentrainer' ),
                        ),
                    ),
                    'required'  => array('top-footer-switch-1', '=', '2'),
                ),
                array(
                    'id'        => 'top-footer-menus-1',
                    'type'      => 'select',
                    'title'     => __( 'Selecteer een Menu', 'sportentrainer' ),
                    'subtitle'  => __( 'Menu voor top footer block 1', 'sportentrainer' ),
                    'required'  => array('top-footer-switch-1', '=', '3'),
                    'data'      => 'menus'
                ),
            array(
                'id'        => 'top-footer-end-1',
                'type'      => 'accordion',
                'class'     => 'topfooterenabled',
                'position'  => 'end'
            ),

            array(
                'id'        => 'top-footer-begin-2',
                'type'      => 'accordion',
                'class'     => 'topfooterenabled',
                'title'     => __( 'Top Footer Blok 2', 'sportentrainer' ),
                'subtitle'  => __('Instellingen voor top footer blok 2', 'sportentrainer'),
                'position'  => 'start',
            ),
                array(
                    'id'        => 'top-footer-switch-2',
                    'type'      => 'button_set',
                    'title'     => __( 'Switch tussen widget en losse elementen', 'sportentrainer' ),
                    'subtitle'  => __( 'Hier kun je kiezen tussen widget of losse elementen met icons (website link of email, etc)', 'sportentrainer' ),
                    'options' => array(
                        '1' => 'Widget', 
                        '2' => 'Elementen', 
                        '3' => 'Menu'
                     ), 
                    'default' => '2'
                ),
                array(
                    'id'        => 'top-footer-widgets-2',
                    'type'      => 'select',
                    'title'     => __( 'Selecteer een Widget Area', 'sportentrainer' ),
                    'subtitle'  => __( 'Widget Area voor top footer block 2', 'sportentrainer' ),
                    'required'  => array('top-footer-switch-2', '=', '1'),
                    'data'      => 'sidebars',
                    'multi'     => true,
                    'sortable'  => true
                ),
                array(
                    'id'            => 'top-footer-elements-repeater-2',
                    'type'          => 'repeater',
                    'title'         => __( 'Title', 'sportentrainer' ),
                    'group_values'  => true,
                    'fields'        => array(
                        array(
                            'id'        => 'top-footer-elements-elem-icon',
                            'type'      => 'icon_select',
                            'title'     => __( 'Icon voor element', 'sportentrainer' ),
                            'subtitle'  => __( 'Selecteer icon voor element, laat leeg voor geen icon.', 'sportentrainer' ),
                            'height'    => '120px',
                            'stylesheet'    => 'http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css',
                            'prefix'    => 'fa',
                            'selector'  => 'fa-',
                        ),
                        array(
                            'id'        => 'top-footer-icon-color',
                            'type'      => 'color',
                            'title'     => __( 'Icon Kleur', 'sportentrainer' ),
                            'subtitle'  => __( 'Kies de kleur voor de icon', 'sportentrainer' ),
                            'default'   => '#FFFFFF',
                            'transparent' => false,
                        ),
                        array(
                            'id'        => 'top-footer-elements-elem-text',
                            'type'      => 'text',
                            'title'     => __( 'Tekst voor element', 'sportentrainer' ),
                            'subtitle'  => __( 'Vul tekst in, dit kan ook een url zijn, dit wordt herkend', 'sportentrainer' ),
                        ),
                    ),
                    'required'  => array('top-footer-switch-2', '=', '2'),
                ),
                array(
                    'id'        => 'top-footer-menus-2',
                    'type'      => 'select',
                    'title'     => __( 'Selecteer een Menu', 'sportentrainer' ),
                    'subtitle'  => __( 'Menu voor top footer block 2', 'sportentrainer' ),
                    'required'  => array('top-footer-switch-2', '=', '3'),
                    'data'      => 'menus'
                ),
            array(
                'id'        => 'top-footer-end-2',
                'type'      => 'accordion',
                'class'     => 'topfooterenabled',
                'position'  => 'end'
            ),

            array(
                'id'        => 'top-footer-begin-3',
                'type'      => 'accordion',
                'class'     => 'topfooterenabled',
                'title'     => __( 'Top Footer Blok 3', 'sportentrainer' ),
                'subtitle'  => __('Instellingen voor top footer blok 3', 'sportentrainer'),
                'position'  => 'start',
            ),
                array(
                    'id'        => 'top-footer-switch-3',
                    'type'      => 'button_set',
                    'title'     => __( 'Switch tussen widget en losse elementen', 'sportentrainer' ),
                    'subtitle'  => __( 'Hier kun je kiezen tussen widget of losse elementen met icons (website link of email, etc)', 'sportentrainer' ),
                    'options' => array(
                        '1' => 'Widget', 
                        '2' => 'Elementen', 
                        '3' => 'Menu'
                     ), 
                    'default' => '2'
                ),
                array(
                    'id'        => 'top-footer-widgets-3',
                    'type'      => 'select',
                    'title'     => __( 'Selecteer een Widget Area', 'sportentrainer' ),
                    'subtitle'  => __( 'Widget Area voor top footer block 3', 'sportentrainer' ),
                    'required'  => array('top-footer-switch-3', '=', '1'),
                    'data'      => 'sidebars',
                    'multi'     => true,
                    'sortable'  => true
                ),
                array(
                    'id'            => 'top-footer-elements-repeater-3',
                    'type'          => 'repeater',
                    'title'         => __( 'Title', 'sportentrainer' ),
                    'group_values'  => true,
                    'fields'        => array(
                        array(
                            'id'        => 'top-footer-elements-elem-icon',
                            'type'      => 'icon_select',
                            'title'     => __( 'Icon voor element', 'sportentrainer' ),
                            'subtitle'  => __( 'Selecteer icon voor element, laat leeg voor geen icon.', 'sportentrainer' ),
                            'height'    => '120px',
                            'stylesheet'    => 'http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css',
                            'prefix'    => 'fa',
                            'selector'  => 'fa-',
                        ),
                        array(
                            'id'        => 'top-footer-icon-color',
                            'type'      => 'color',
                            'title'     => __( 'Icon Kleur', 'sportentrainer' ),
                            'subtitle'  => __( 'Kies de kleur voor de icon', 'sportentrainer' ),
                            'default'   => '#FFFFFF',
                            'transparent' => false,
                        ),
                        array(
                            'id'        => 'top-footer-elements-elem-text',
                            'type'      => 'text',
                            'title'     => __( 'Tekst voor element', 'sportentrainer' ),
                            'subtitle'  => __( 'Vul tekst in, dit kan ook een url zijn, dit wordt herkend', 'sportentrainer' ),
                        ),
                    ),
                    'required'  => array('top-footer-switch-3', '=', '2'),
                ),
                array(
                    'id'        => 'top-footer-menus-3',
                    'type'      => 'select',
                    'title'     => __( 'Selecteer een Menu', 'sportentrainer' ),
                    'subtitle'  => __( 'Menu voor top footer block 3', 'sportentrainer' ),
                    'required'  => array('top-footer-switch-3', '=', '3'),
                    'data'      => 'menus'
                ),
            array(
                'id'        => 'top-footer-end-3',
                'type'      => 'accordion',
                'class'     => 'topfooterenabled',
                'position'  => 'end'
            ),
        )
    ) );`

**Comment by kprovance** [comment] 2017-05-01 21:27
So far, I am unable to reproduce this issue.  Are you running this in an environment that has internet access?  Using a stylesheet from another server means WP and Redux needs to connect to the internet to retrieve it, and the error you are reporting suggests wp_remote_get is failing.  But I am unable to make that call fail, so I wonder if it's a local issue?

**Comment by udarts** [comment] 2017-05-02 06:10
Hi, yeah the error seems to happen randomly, with me know it works as well. Could be a local issue. I will check. The icons are being loaded from fontawesome, that could be the reason. But like I said, it's happening randomly.

**Comment by kprovance** [comment] 2017-05-02 09:03
Thing is wp_remote_get is a WordPress API, which we have no control over, and then becomes a server setup issue.  The best we can do is add some trap code to catch the error, but the end result would be the same, no icons displayed should the style sheet not load.  You always include the stylesheet with your theme, and not worry about it.  Anyways, closing this ticket.

**Closed by kprovance** 2017-05-02 09:03 UTC

**Comment by cputer** [comment] 2017-12-08 00:33
It must be PHP 7+ related.
