### ISSUE TITLE
Datetime extension CSS issue

### ISSUE THREAD

**Issue by isoaah** [reduxframework/redux-extensions#224] opened 2015-08-23 12:56 UTC
Hello.
I am experiencing a weird bug in Datetime extension. Not sure when it appeared, I've noticed it just now.
http://s27.postimg.org/hze1cdudf/datetime_ext_bug.jpg

I am running Redux plugin 3.5.6.1, WP 4.3 and Datetime 1.0.4. Any ideas?

**Comment by kprovance** [comment] 2015-08-23 16:25
I cannot reproduce.  First, I would see if another plugin is loading some rogue or outdated version of jquery-ui CSS.  We're also up to Redux 3.5.6.6.

**Comment by isoaah** [comment] 2015-08-23 17:18
So I've tested it on 3.5.4.3 and there was no issue. I've updated to 3.5.6.1, issue appears. I've updated to 3.5.6.7 and it still persists. All 3rd party plugins are disabled. Any hints where should I look at? In which CSS file should be those missing definitions? redux-framework/ReduxCore/assets/css/vendor/jquery-ui-bootstrap/jquery-ui-1.10.0.custom.css seems to be fine, any other file?

**Comment by kprovance** [comment] 2015-08-23 19:19
Email me at kevin@reduxframework.com.  I have a potential fix that I want to ensure work before updating the the site with it.

**Comment by kprovance** [comment] 2015-08-23 20:27
Issue resolved with new version 1.0.5, which shall be posted to the Redux extensions site here shortly.  :)

**Closed by kprovance** 2015-08-23 20:27 UTC
