### ISSUE TITLE
Repeater & PHP 7.1

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-extensions#312] opened 2016-12-22 14:18 UTC
- WordPress 4.7
- Redux Framework: 3.6.3 ( Latest WP.org Release )
- Repeater Extension: 1.0.4

//---//

Hi, I used the repeater extension and with PHP 7.1 not work and break the wordpress functionality.

I can navigate in wordpress admin area, but when edit a page, post or custom post type appear this ( some fields about repeater ): https://cl.ly/272C2m0d2i10

This error appear if present the repeater field in a metabox or theme options panel.

If I use for example a version of PHP < of 7.1 all works perfectly without any problem.

I cannot generate the support URL, generate an error: https://cl.ly/1L1p2O283u0R

**Comment by Bluxart** [comment] 2017-01-15 17:26
Any news?

**Comment by Bluxart** [comment] 2017-01-30 11:21
I have this error with PHP 7.1

https://cl.ly/250p273S0l09

**Comment by kprovance** [comment] 2017-01-30 11:58
Having your support hash would also help out.  Dovy will eventually ask for it, or at least your options config

**Comment by Bluxart** [comment] 2017-01-30 12:05
The main problem is can't give you the support hash, because my online server not have PHP 7+, instead my local envoriment ( MAMP ) has the new version of PHP.

However for replicate the issue, is simple just create the Repeater field ( repeater extensions ) and insert the rgba field inside.

This error appear only if you navigate the post, page, custom post type.

**Comment by Bluxart** [comment] 2017-01-30 12:15
However this is the option config:

```php

array(
    'id' => 'az_palette_items',
    'type' => 'repeater',
    'title' => __( 'Palette Items', 'valkyrie' ),
    'subtitle' => __( 'Unlimited palette color items.', 'valkyrie' ),
    'group_values' => true,
    'fields' => array(

        array(
            'id' => 'az_palette_reference',
            'type' => 'text',
            'title' => __( 'Reference Name', 'valkyrie' ),
            'desc' => __( 'Set a reference name for this palette item.', 'valkyrie' ),
            'default' => '',
        ),

        array(
            'id' => 'az_palette_id',
            'type' => 'text',
            'class' => 'az-palette-unique-id',
            'title' => __( 'Unique ID', 'valkyrie' ),
            'desc' => __( 'Set an unique ID name for this palette item.', 'valkyrie' ),
            'default' => '',
        ),

        array(
            'id' => 'az_palette_style',
            'type'  => 'button_set',
            'title' => __( 'Style', 'valkyrie' ), 
            'desc'  => __( 'Choose if this palette item is a monochrome or gradient color.', 'valkyrie' ),
            'options' => array(
                'monochrome' => __( 'Monochrome', 'valkyrie' ),
                'gradient' => __( 'Gradient', 'valkyrie' ),
            ),
            'default' => 'monochrome',
        ),
        array(
            'id' => 'az_palette_color',
            'type' => 'color_rgba',
            'title' => __( 'Color', 'valkyrie' ),
            'desc' => __( 'Choose a solid color for this palette item.', 'valkyrie' ),
            'validate' => 'colorrgba',
            'transparent' => false,
            'options' => array(
                'show_input' => true,
                'show_initial' => false,
                'show_alpha' => true,
                'show_palette' => true,
                'show_palette_only'  => false,
                'show_selection_palette' => true,
                'max_palette_size' => 10,
                'allow_empty' => true,
                'clickout_fires_change'  => true,
                'choose_text' => 'Choose',
                'cancel_text' => 'Cancel',
                'show_buttons' => true,
                'use_extended_classes'  => true,
                'palette'      => null,
                'input_text' => 'Select Color'
            ),
            'default' => array( 'color' => '#000000', 'alpha' => '1' ),
        ),

        array(
            'id'      => 'az_palette_gradient',
            'type'  => 'text',
            'title'   => __( 'Gradient', 'valkyrie' ), 
            'desc' => __( 'Choose a gradient color for this palette item.', 'valkyrie' ),
            'default' => '',
        ),

    ),
),

```

**Comment by kprovance** [comment] 2017-01-30 12:25
It doesnt matter if it's local or not, the support hash is encrypted data about your config, and it way more helpful.

**Comment by Bluxart** [comment] 2017-01-30 12:28
Ah ok but not work, return me a 413 error: https://cl.ly/3r1q1f0x2B2c

**Comment by kprovance** [comment] 2017-01-30 12:29
That means one of the php.ini settings is too small to handle the input necessary.

**Comment by kprovance** [comment] 2017-01-30 12:49
Try removing

```
'validate' => 'colorrgba',
```

And see what happens.  It's not needed, and doesn't work anyway.

**Comment by Bluxart** [comment] 2017-01-30 13:00
I see the Redux Status and all PHP Settings is green, how settings need to override to work the support hash?

However I tested to removed this string:
`'validate' => 'colorrgba',`

But have the same issue, not change anything same warning and fatal error.

**Comment by kprovance** [comment] 2017-01-30 13:01
Okay, @Dovy is going to have to fix this, then.  I am not running PHP 7 (I cant, my OS is too old) and cannot reproduce.  Sorry, I gave it my best shot.

**Comment by dovy** [comment] 2017-01-30 16:42
Hey there, sorry for the delay. I'm trying to overhaul the entire repeater field. If I can't get it resolved in the next few days, I'll just get you a PHP7 fix really quick.

Sorry for the delay. Trying to fix it right!

**Comment by dovy** [comment] 2017-01-30 16:42
Oh wait, you have a 413! That means your repeater is HUGE. You may need to turn off Ajax save completely...

**Comment by Bluxart** [comment] 2017-01-30 17:08
I try to deactivate the Ajax Save, but the i have always a 413 error, the config file is very huge. Let me know if you can resolve this.

Thanks

**Comment by kprovance** [comment] 2017-01-30 17:11
I don't know if we can resolve a huge config file, short of redesigning it, and that's not a free service.

**Comment by Bluxart** [comment] 2017-01-30 17:25
I want news for the PHP fix ( if possible ) not for the support hash. In meanwhile try to re-create a short config file and send the support hash.

**Closed** 2023-06-18 01:22 UTC
